/*
# Test the Server API
*/
@host  http://localhost:8080
###
GET /api/produce.json

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 4099
etag: W/"1003-JLbDbt25prBvbuHoLwv5i016cFU"
date: Thu, 27 Mar 2025 14:00:12 GMT
connection: close
###
GET /api/produce/67e40f14c19ec4a1c06b141e.json

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 210
etag: W/"d2-lv7EcN72/9+gEqfBNa/R/ANj+cg"
date: Thu, 27 Mar 2025 14:00:20 GMT
connection: close
###
GET /api/documents.json
###
GET /api/produce/67e40f14c19ec4a1c06b141a.json

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 206
etag: W/"ce-dplAVnUXXZCdZELN+Wmul3rNFUQ"
date: Thu, 27 Mar 2025 14:00:59 GMT
connection: close